#!/usr/bin/env bash
# Bash script that displays:
# To infinity and beyond indefinitely
# With a sleep 2 in between each iteration
# I am invincible!!! when receiving a SIGTERM signal
do
	echo "To infinity and beyond"
	sleep 2
	trap "'I am invincible!!!'" SIGTERM
done
