#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59
minute=60
hour=0
while [ $minute -le 60 ]
do
	if [ $minute -eq 60 ];then
		if [ $hour -gt 12 ];then
			break
		fi
		echo "Hour: $hour"
		minute=0
		hour=$((hour+1))
	else
		echo "$minute"
	fi
	minute=$((minute+1))
done
